### PR TITLE
Fixes Issue #9 - Added routing from projects list to project page

### PR DESCRIPTION
**Pull request by minimatrix**
- Added routing from projects list to Project page
- Moved data from Home.js into a JSON object for easy inclusion in other files
- Added keys when mapping the Projects 
- Updated Project.js to reference the new json file to render all information for a project
- made cursor "pointer" when hovering items in the project list

### CODE REVIEW

**Comment by pranjaljain0** [comment]
Good work @minimatrix I really liked your work, Keep it up.

**Comment by jonnycbw** [comment]
Thanks, this was my first OSS contribution :)

**Comment by minimatrix** [comment]
Thanks, this was my first OSS contribution :)

**Comment by jonnycbw** [comment]
@pranjaljain0 - would you kindly be able to add your project to the hacktoberfest topic. My pull request was declined because the repo isn't eligible without the topic.

**Comment by pranjaljain0** [comment]
Sure thing

**Comment by pranjaljain0** [comment]
@jonnycbw Done that :) 🥇

**Pull request merged**
